# Generated by Django 5.2.6 on 2025-09-16 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w2_job_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='w2job',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='w2job',
            name='file_type',
        ),
        migrations.AddField(
            model_name='w2job',
            name='file_uploaded',
            field=models.BooleanField(default=False),
        ),
    ]
