# Generated by Django 5.2.6 on 2025-09-22 08:47

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w2_job_app', '0002_remove_w2job_file_size_remove_w2job_file_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='w2job',
            name='external_data_update',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='w2job',
            name='external_upload',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='W2Data',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ein', models.CharField(blank=True, max_length=20, null=True)),
                ('ssn', models.CharField(blank=True, max_length=20, null=True)),
                ('wages_box1', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('federal_tax_withheld_box2', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('w2_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='w2_data', to='w2_job_app.w2job')),
            ],
            options={
                'db_table': 'w2_data',
                'ordering': ['-created_at'],
            },
        ),
    ]
