# Generated by Django 5.2.6 on 2025-09-22 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('w2_job_app', '0003_w2job_external_data_update_w2job_external_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='w2data',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='w2data',
            name='status_msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='w2job',
            name='w2_data_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='w2job',
            name='w2_data_status_msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
