# Generated by Django 5.2.6 on 2025-09-22 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w2_job_app', '0004_w2data_status_w2data_status_msg_w2job_w2_data_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='w2data',
            name='status',
        ),
        migrations.RemoveField(
            model_name='w2data',
            name='status_msg',
        ),
    ]
